FROM node:22 AS build

# Setting working directory.
WORKDIR /opt/meilisearch-ui

RUN npm install -g pnpm

# Copying source files
COPY . .

# Installing dependencies
RUN pnpm install

# Build the app
RUN npm run build

# -------
FROM nginx:stable-alpine AS final

# Install dependencies for injecting the BASE_PATH into config
RUN apk add --no-cache gettext sed

COPY --from=build /opt/meilisearch-ui/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.basepath.conf.template /etc/nginx/templates/
COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

# Default to root
ENV BASE_PATH=""
EXPOSE 24900

CMD ["/docker-entrypoint.sh"]