/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarningImport } from './routes/warning'
import { Route as IndexImport } from './routes/index'
import { Route as InsInsIDLayoutImport } from './routes/ins/$insID/_layout'
import { Route as InsInsIDLayoutIndexImport } from './routes/ins/$insID/_layout/index'
import { Route as InsInsIDLayoutTasksImport } from './routes/ins/$insID/_layout/tasks'
import { Route as InsInsIDLayoutKeysImport } from './routes/ins/$insID/_layout/keys'
import { Route as InsInsIDLayoutIndexIndexUIDLayoutImport } from './routes/ins/$insID/_layout/index/$indexUID/_layout'
import { Route as InsInsIDLayoutIndexIndexUIDLayoutIndexImport } from './routes/ins/$insID/_layout/index/$indexUID/_layout/index'
import { Route as InsInsIDLayoutIndexIndexUIDLayoutSettingImport } from './routes/ins/$insID/_layout/index/$indexUID/_layout/setting'
import { Route as InsInsIDLayoutIndexIndexUIDLayoutDocumentsIndexImport } from './routes/ins/$insID/_layout/index/$indexUID/_layout/documents/index'
import { Route as InsInsIDLayoutIndexIndexUIDLayoutDocumentsUploadImport } from './routes/ins/$insID/_layout/index/$indexUID/_layout/documents/upload'

// Create Virtual Routes

const InsInsIDImport = createFileRoute('/ins/$insID')()
const InsInsIDLayoutIndexIndexUIDImport = createFileRoute(
  '/ins/$insID/_layout/index/$indexUID',
)()

// Create/Update Routes

const WarningRoute = WarningImport.update({
  path: '/warning',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InsInsIDRoute = InsInsIDImport.update({
  path: '/ins/$insID',
  getParentRoute: () => rootRoute,
} as any)

const InsInsIDLayoutRoute = InsInsIDLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => InsInsIDRoute,
} as any)

const InsInsIDLayoutIndexRoute = InsInsIDLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => InsInsIDLayoutRoute,
} as any)

const InsInsIDLayoutTasksRoute = InsInsIDLayoutTasksImport.update({
  path: '/tasks',
  getParentRoute: () => InsInsIDLayoutRoute,
} as any)

const InsInsIDLayoutKeysRoute = InsInsIDLayoutKeysImport.update({
  path: '/keys',
  getParentRoute: () => InsInsIDLayoutRoute,
} as any)

const InsInsIDLayoutIndexIndexUIDRoute =
  InsInsIDLayoutIndexIndexUIDImport.update({
    path: '/index/$indexUID',
    getParentRoute: () => InsInsIDLayoutRoute,
  } as any)

const InsInsIDLayoutIndexIndexUIDLayoutRoute =
  InsInsIDLayoutIndexIndexUIDLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => InsInsIDLayoutIndexIndexUIDRoute,
  } as any)

const InsInsIDLayoutIndexIndexUIDLayoutIndexRoute =
  InsInsIDLayoutIndexIndexUIDLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => InsInsIDLayoutIndexIndexUIDLayoutRoute,
  } as any)

const InsInsIDLayoutIndexIndexUIDLayoutSettingRoute =
  InsInsIDLayoutIndexIndexUIDLayoutSettingImport.update({
    path: '/setting',
    getParentRoute: () => InsInsIDLayoutIndexIndexUIDLayoutRoute,
  } as any)

const InsInsIDLayoutIndexIndexUIDLayoutDocumentsIndexRoute =
  InsInsIDLayoutIndexIndexUIDLayoutDocumentsIndexImport.update({
    path: '/documents/',
    getParentRoute: () => InsInsIDLayoutIndexIndexUIDLayoutRoute,
  } as any)

const InsInsIDLayoutIndexIndexUIDLayoutDocumentsUploadRoute =
  InsInsIDLayoutIndexIndexUIDLayoutDocumentsUploadImport.update({
    path: '/documents/upload',
    getParentRoute: () => InsInsIDLayoutIndexIndexUIDLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/warning': {
      id: '/warning'
      path: '/warning'
      fullPath: '/warning'
      preLoaderRoute: typeof WarningImport
      parentRoute: typeof rootRoute
    }
    '/ins/$insID': {
      id: '/ins/$insID'
      path: '/ins/$insID'
      fullPath: '/ins/$insID'
      preLoaderRoute: typeof InsInsIDImport
      parentRoute: typeof rootRoute
    }
    '/ins/$insID/_layout': {
      id: '/ins/$insID/_layout'
      path: '/ins/$insID'
      fullPath: '/ins/$insID'
      preLoaderRoute: typeof InsInsIDLayoutImport
      parentRoute: typeof InsInsIDRoute
    }
    '/ins/$insID/_layout/keys': {
      id: '/ins/$insID/_layout/keys'
      path: '/keys'
      fullPath: '/ins/$insID/keys'
      preLoaderRoute: typeof InsInsIDLayoutKeysImport
      parentRoute: typeof InsInsIDLayoutImport
    }
    '/ins/$insID/_layout/tasks': {
      id: '/ins/$insID/_layout/tasks'
      path: '/tasks'
      fullPath: '/ins/$insID/tasks'
      preLoaderRoute: typeof InsInsIDLayoutTasksImport
      parentRoute: typeof InsInsIDLayoutImport
    }
    '/ins/$insID/_layout/': {
      id: '/ins/$insID/_layout/'
      path: '/'
      fullPath: '/ins/$insID/'
      preLoaderRoute: typeof InsInsIDLayoutIndexImport
      parentRoute: typeof InsInsIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID': {
      id: '/ins/$insID/_layout/index/$indexUID'
      path: '/index/$indexUID'
      fullPath: '/ins/$insID/index/$indexUID'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDImport
      parentRoute: typeof InsInsIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID/_layout': {
      id: '/ins/$insID/_layout/index/$indexUID/_layout'
      path: '/index/$indexUID'
      fullPath: '/ins/$insID/index/$indexUID'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutImport
      parentRoute: typeof InsInsIDLayoutIndexIndexUIDRoute
    }
    '/ins/$insID/_layout/index/$indexUID/_layout/setting': {
      id: '/ins/$insID/_layout/index/$indexUID/_layout/setting'
      path: '/setting'
      fullPath: '/ins/$insID/index/$indexUID/setting'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutSettingImport
      parentRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID/_layout/': {
      id: '/ins/$insID/_layout/index/$indexUID/_layout/'
      path: '/'
      fullPath: '/ins/$insID/index/$indexUID/'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutIndexImport
      parentRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID/_layout/documents/upload': {
      id: '/ins/$insID/_layout/index/$indexUID/_layout/documents/upload'
      path: '/documents/upload'
      fullPath: '/ins/$insID/index/$indexUID/documents/upload'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutDocumentsUploadImport
      parentRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID/_layout/documents/': {
      id: '/ins/$insID/_layout/index/$indexUID/_layout/documents/'
      path: '/documents'
      fullPath: '/ins/$insID/index/$indexUID/documents'
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutDocumentsIndexImport
      parentRoute: typeof InsInsIDLayoutIndexIndexUIDLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WarningRoute,
  InsInsIDRoute: InsInsIDRoute.addChildren({
    InsInsIDLayoutRoute: InsInsIDLayoutRoute.addChildren({
      InsInsIDLayoutKeysRoute,
      InsInsIDLayoutTasksRoute,
      InsInsIDLayoutIndexRoute,
      InsInsIDLayoutIndexIndexUIDRoute:
        InsInsIDLayoutIndexIndexUIDRoute.addChildren({
          InsInsIDLayoutIndexIndexUIDLayoutRoute:
            InsInsIDLayoutIndexIndexUIDLayoutRoute.addChildren({
              InsInsIDLayoutIndexIndexUIDLayoutSettingRoute,
              InsInsIDLayoutIndexIndexUIDLayoutIndexRoute,
              InsInsIDLayoutIndexIndexUIDLayoutDocumentsUploadRoute,
              InsInsIDLayoutIndexIndexUIDLayoutDocumentsIndexRoute,
            }),
        }),
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/warning",
        "/ins/$insID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/warning": {
      "filePath": "warning.tsx"
    },
    "/ins/$insID": {
      "filePath": "ins/$insID",
      "children": [
        "/ins/$insID/_layout"
      ]
    },
    "/ins/$insID/_layout": {
      "filePath": "ins/$insID/_layout.tsx",
      "parent": "/ins/$insID",
      "children": [
        "/ins/$insID/_layout/keys",
        "/ins/$insID/_layout/tasks",
        "/ins/$insID/_layout/",
        "/ins/$insID/_layout/index/$indexUID"
      ]
    },
    "/ins/$insID/_layout/keys": {
      "filePath": "ins/$insID/_layout/keys.tsx",
      "parent": "/ins/$insID/_layout"
    },
    "/ins/$insID/_layout/tasks": {
      "filePath": "ins/$insID/_layout/tasks.tsx",
      "parent": "/ins/$insID/_layout"
    },
    "/ins/$insID/_layout/": {
      "filePath": "ins/$insID/_layout/index.tsx",
      "parent": "/ins/$insID/_layout"
    },
    "/ins/$insID/_layout/index/$indexUID": {
      "filePath": "ins/$insID/_layout/index/$indexUID",
      "parent": "/ins/$insID/_layout",
      "children": [
        "/ins/$insID/_layout/index/$indexUID/_layout"
      ]
    },
    "/ins/$insID/_layout/index/$indexUID/_layout": {
      "filePath": "ins/$insID/_layout/index/$indexUID/_layout.tsx",
      "parent": "/ins/$insID/_layout/index/$indexUID",
      "children": [
        "/ins/$insID/_layout/index/$indexUID/_layout/setting",
        "/ins/$insID/_layout/index/$indexUID/_layout/",
        "/ins/$insID/_layout/index/$indexUID/_layout/documents/upload",
        "/ins/$insID/_layout/index/$indexUID/_layout/documents/"
      ]
    },
    "/ins/$insID/_layout/index/$indexUID/_layout/setting": {
      "filePath": "ins/$insID/_layout/index/$indexUID/_layout/setting.tsx",
      "parent": "/ins/$insID/_layout/index/$indexUID/_layout"
    },
    "/ins/$insID/_layout/index/$indexUID/_layout/": {
      "filePath": "ins/$insID/_layout/index/$indexUID/_layout/index.tsx",
      "parent": "/ins/$insID/_layout/index/$indexUID/_layout"
    },
    "/ins/$insID/_layout/index/$indexUID/_layout/documents/upload": {
      "filePath": "ins/$insID/_layout/index/$indexUID/_layout/documents/upload.tsx",
      "parent": "/ins/$insID/_layout/index/$indexUID/_layout"
    },
    "/ins/$insID/_layout/index/$indexUID/_layout/documents/": {
      "filePath": "ins/$insID/_layout/index/$indexUID/_layout/documents/index.tsx",
      "parent": "/ins/$insID/_layout/index/$indexUID/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
