/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarningImport } from './routes/warning'
import { Route as IndexImport } from './routes/index'
import { Route as InsInsIDLayoutImport } from './routes/ins/$insID/_layout'
import { Route as InsInsIDLayoutIndexImport } from './routes/ins/$insID/_layout/index'
import { Route as InsInsIDLayoutIndexIndexUIDIndexImport } from './routes/ins/$insID/_layout/index/$indexUID/index'

// Create Virtual Routes

const InsInsIDImport = createFileRoute('/ins/$insID')()

// Create/Update Routes

const WarningRoute = WarningImport.update({
  path: '/warning',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InsInsIDRoute = InsInsIDImport.update({
  path: '/ins/$insID',
  getParentRoute: () => rootRoute,
} as any)

const InsInsIDLayoutRoute = InsInsIDLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => InsInsIDRoute,
} as any)

const InsInsIDLayoutIndexRoute = InsInsIDLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => InsInsIDLayoutRoute,
} as any)

const InsInsIDLayoutIndexIndexUIDIndexRoute =
  InsInsIDLayoutIndexIndexUIDIndexImport.update({
    path: '/index/$indexUID/',
    getParentRoute: () => InsInsIDLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/warning': {
      preLoaderRoute: typeof WarningImport
      parentRoute: typeof rootRoute
    }
    '/ins/$insID': {
      preLoaderRoute: typeof InsInsIDImport
      parentRoute: typeof rootRoute
    }
    '/ins/$insID/_layout': {
      preLoaderRoute: typeof InsInsIDLayoutImport
      parentRoute: typeof InsInsIDRoute
    }
    '/ins/$insID/_layout/': {
      preLoaderRoute: typeof InsInsIDLayoutIndexImport
      parentRoute: typeof InsInsIDLayoutImport
    }
    '/ins/$insID/_layout/index/$indexUID/': {
      preLoaderRoute: typeof InsInsIDLayoutIndexIndexUIDIndexImport
      parentRoute: typeof InsInsIDLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WarningRoute,
  InsInsIDRoute.addChildren([
    InsInsIDLayoutRoute.addChildren([
      InsInsIDLayoutIndexRoute,
      InsInsIDLayoutIndexIndexUIDIndexRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
