name: release-please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    name: Release pls
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: release-please-config.json

      - name: Echo status of release-please
        env:
          RELEASES_CREATED: ${{ steps.release.outputs.releases_created }}
          RELEASE_CREATED: ${{ steps.release.outputs.release_created }}
          RELEASE_CREATED_PR: ${{ steps.release.outputs.prs_created }}
        run: |
          echo "releases_created: $RELEASES_CREATED"
          echo "release_created: $RELEASE_CREATED"
          echo "release_created_pr: $RELEASE_CREATED_PR"
